Vagrant.configure("2") do |config|
    config.vm.synced_folder ".", "/vagrant", type: "rsync"
    config.vm.box = "debian/bookworm64"
    config.vm.synced_folder "../confs", "/confs", type: "rsync"

    config.vm.provider :libvirt do |lv|
        lv.cpus = 1
        lv.memory = "2048"
    end

    config.vm.define "bobS" do |server|
        server.vm.hostname = "bobS" 
        server.vm.network "private_network", 
            ip: "192.168.56.110"
        server.vm.provision "shell", path: "../scripts/provision-k3s.sh"
    end
end
