Vagrant.configure("2") do |config|
    config.vm.synced_folder ".", "/vagrant", type: "rsync", disabled: true
    config.vm.box = "debian/bookworm64"
    config.vm.synced_folder "/home/bde-albu/Inception-of-Things/p2/confs", "/home/vagrant/confs", type: "rsync"
    config.vm.synced_folder "/home/bde-albu/bin/k3s-offline", "/home/vagrant/k3s-offline", type: "rsync"

    config.vm.provider :libvirt do |lv|
        lv.cpus = 1
        lv.memory = "2048"
    end

    config.vm.define "bobS" do |server|
        server.vm.hostname = "bobS" 
        server.vm.network "private_network", 
            ip: "192.168.56.110"
        server.vm.provision "shell", path: "../scripts/provision-k3s.sh"
    end
end