apiVersion: v1
kind: Pod
metadata:
  name: gitlab
  namespace: gitlab
  labels:
    app: gitlab
spec:
  containers:
  - name: gitlab
    image: gitlab/gitlab-ce:latest
    securityContext:
      runAsUser: 0
    ports:
    - containerPort: 80
    - containerPort: 443
    - containerPort: 22
    env:
    - name: GITLAB_OMNIBUS_CONFIG
      value: |
        external_url 'http://gitlab.localhost';
        nginx['listen_port'] = 80;
        nginx['listen_https'] = false;
        gitlab_rails['gitlab_shell_ssh_port'] = 32000;
        puma['worker_processes']=0;
        sidekiq['concurrency']=1;
        gitaly['cgroups_enabled'] = false;
        gitaly['env'] = {
          'GITALY_COMMAND_SPAWN_MAX_PARALLEL' => '2'
        };
        prometheus_monitoring['enable'] = false;
        gitlab_rails['env'] = {
          'MALLOC_CONF' => 'dirty_decay_ms:1000,muzzy_decay_ms:1000'
        };
        gitaly['env'] = {
          'MALLOC_CONF' => 'dirty_decay_ms:1000,muzzy_decay_ms:1000'
        };
