ENV['VAGRANT_NO_PARALLEL'] = 'yes'
Vagrant.configure("2") do |config|
    config.vm.synced_folder ".", "/vagrant", type: "rsync", disabled: true
    config.vm.box = "debian/bookworm64"

    config.vm.provider :libvirt do |lv|
        lv.cpus = 1
        lv.memory = "1024"
    end

    config.vm.define "bob" do |server|
        server.vm.hostname = "bob" 
        server.vm.network "private_network", 
            ip: "192.168.56.110"
        server.vm.provision "shell", path: "../scripts/server.sh"
    end
    config.vm.define "kevin" do |server|
        server.vm.hostname = "kevin" 
        server.vm.network "private_network", 
            ip: "192.168.56.111"
        server.vm.provision "shell", path: "../scripts/worker.sh"
    end
end
